### ISSUE TITLE
miss dockerfile for client

### ISSUE THREAD

**Issue by frikyalong** [martindavid/flask-react-docker-app#2]
hi author,
I can not find the dockerfile for client folder.

**Comment by kaliszKrzysztof** [comment]
@frikyalong Try to use `Dockerfile` from https://medium.com/better-programming/setup-flask-nextjs-application-with-docker-97e82a897573. It worked in my case.

**Comment by martindavid** [comment]
Hi @frikyalong, good catch. I've updated the repo to include. @kaliszKrzysztof Thanks for jump in and answer it.
